name: Test Kitchen

on:
  - push
  - pull_request
  - workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  kitchen-requirements:
    name: Check Kitchen Requirements
    runs-on: ubuntu-latest
    outputs:
      requirements: ${{ steps.requirements.outputs.requirements }}
    steps:
    - name: Check out code
      uses: actions/checkout@v5
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run kitchen list
      id: requirements
      run: |
        bundle exec kitchen list --json | jq 'map(del(.last_action, .last_error))' | tee matrix.json
        echo "requirements=$(jq -c . matrix.json)" >> "$GITHUB_OUTPUT"

  kitchen:
    name: Test Kitchen
    runs-on: ubuntu-latest
    needs: kitchen-requirements
    permissions:
      packages: read
    strategy:
      matrix:
        include: ${{ fromJson(needs.kitchen-requirements.outputs.requirements) }}
      fail-fast: false
    steps:
    - name: Test Kitchen Info
      run: |
        echo "Instance:    ${{ matrix.instance }}"
        echo "Driver:      ${{ matrix.driver }}"
        echo "Provisioner: ${{ matrix.provisioner }}"
        echo "Verifier:    ${{ matrix.verifier }}"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Check out code
      uses: actions/checkout@v5
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run kitchen test ${{ matrix.instance }}
      run: bundle exec kitchen test ${{ matrix.instance }}
    - name: Gather journal output
      run: |
        bundle exec kitchen exec ${{ matrix.instance }} -c "journalctl --since=yesterday"
        bundle exec kitchen exec ${{ matrix.instance }} -c "networkctl status --all"
        bundle exec kitchen exec ${{ matrix.instance }} -c "resolvectl status" || true
      if: ${{ failure() }}
